### ISSUE TITLE
Feature Extraction: iteration gets stuck  on some websites. 

### ISSUE THREAD

**Issue by Neelrayal** [shreyagopal/Phishing-Website-Detection-by-Machine-Learning-Techniques#5]
I was trying to implement your project. In feature extraction, while combining all the features into one list, the iteration gets stuck on a website. I have to click here and there manually on colab for resuming its execution. How did you run the feature extraction, or am I missing something?

**Comment by sn-chege** [comment]
Did you find a solution to this issue? I am stuck on it

**Comment by Neelrayal** [comment]
Yes, I have made the changes. I can post the solution if you want.

**Comment by chege99** [comment]
Kindly share the solution with me. Please include the pickle file for your final build if you can

**Comment by sn-chege** [comment]
Kindly share the solution. Please include the pickle file for your final build if you can

**Comment by Neelrayal** [comment]
Sorry for the late reply. Was busy with college work. I cannot share the ipynb file here. I am sending you the mega link of my colab file. Just make some small changes which are obvious. 
[file link](https://mega.nz/file/nhoQXRaC#cEaXCasdkkFKwH8DTf5YDyezArJxt_lBB8mEgOdsPSM)

**Comment by ghost** [comment]
How should I get from this file to your code?

**Comment by Neelrayal** [comment]
> 



> How should I get from this file to your code?

https://github.com/Neelrayal/Phishing-website-detection-using-ML

**Comment by ghost** [comment]
thank you 👍
